project:
  type: website

website:
  title: "25W-PIC 16B"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
  page-footer: "Copyright 2025, Ziyan Xie"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
